### PR TITLE
Fix TS types

### LINKED ISSUE #7: Typescript types are wrong
this plugin declared type is not compatible with fastify.register(...), leading to a compile error

repro:
1) create a .ts file with
```ts
import fastify from "fastify";
import fastifyHealth from "fastify-healthcheck";

fastify().register(fastifyHealth);
```
2) try to compile it

expected: compile succeeds
actual: compile fails with 
```
Argument of type 'FastifyMiddleware<Server, IncomingMessage, ServerResponse, DefaultQuery, DefaultParams, DefaultHeaders, any>' is not assignable to parameter of type '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse>, options: FastifyReply<ServerResponse>, callback: (err?: FastifyError | undefined) => void) => void'.
  Types of parameters 'req' and 'instance' are incompatible.
    Type 'FastifyInstance<Server, IncomingMessage, ServerResponse>' is missing the following properties from type 'FastifyRequest<IncomingMessage, DefaultQuery, DefaultParams, DefaultHeaders, any>': query, params, headers, body, and 8 more.ts(2345)
```

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #7

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -1,12 +1,19 @@
...
   healthcheckUrl?: string
   healthcheckUrlDisable?: boolean
   healthcheckUrlAlwaysFail?: boolean
   exposeUptime?: boolean
   underPressureOptions?: Record<string, any>
 }
 
-declare const healthcheckPlugin: FastifyMiddleware<HealthcheckPluginOptions>
-export default healthcheckPlugin
+export const fastifyHealthcheck: fastify.Plugin<
```
Comment (kibertoad) [inline types/index.d.ts:12]: Renamed to be more consistent with other fastify plugin naming

File: package.json [hunk 2]
```diff
@@ -20,21 +20,26 @@
...
   "dependencies": {
     "under-pressure": "^4.0.0"
   },
   "devDependencies": {
+    "@typescript-eslint/eslint-plugin": "^3.0.2",
+    "@typescript-eslint/parser": "^3.0.2",
     "fastify": "^2.14.1",
     "simple-get": "^4.0.0",
     "standard": "^14.3.4",
+    "standardx": "^5.0.0",
```
Comment (kibertoad) [inline package.json:42]: linting is important because previously type mismatch was obscured due to `require` used instead of `import` in test. Linter caught that immediately.

File: types/index.d.ts (hunk 1 above)
Comment (smartiniOnGitHub) [reply types/index.d.ts:12]: very good

File: package.json (hunk 2 above)
Comment (smartiniOnGitHub) [reply package.json:42]: perfect, thanks
